### ISSUE TITLE
Release to Maven

### ISSUE THREAD

**Issue by maksymkovalenko** [unitsofmeasurement/jackson-module-unitsofmeasure#10]
Hey, I can't find this releases of this project in Maven:
https://mvnrepository.com/search?q=com.opower.unitsofmeasure
http://search.maven.org/#search%7Cga%7C1%7Ccom.opower.unitsofmeasure

Any plans to add it?

P.S. Other projects (API, implementation) are released to Maven.

**Comment by keilw** [comment]
It's a bit more complicated here I'm afraid. JCenter is less strict when it comes to groupIds and publish rights to its Maven repositories. Complying to what's needed (e.g. sources, etc.) is usually fine. MavenCentral in its JIRA system asks for how you participate in a project. And we're not the original authors of the Opower project, it's a "fork" if you want or a PR they never merged.
Opower was acquired by Oracle over a year ago. What it published to MavenCentral are things like https://search.maven.org/#search%7Cga%7C1%7Ccom.opower, but unitsofmeasure was never published by them. According to GitHub @jeffkole maintains it and now took it outside Opower, guess he no longer works there. If he was happy to publish it to MavenCentral, or approves "uom" to do so, we can, otherwise I'm afraid that has to wait for an independent new port in our package space (tec.uom or similar) 
If you have a use case and were happy to contribute, we could do something like it under https://github.com/unitsofmeasurement/uom-lib. The ultimate plan is to use https://github.com/javaee/jsonb-spec instead of Jackson.

**Comment by maksymkovalenko** [comment]
Honestly, I was surprised to see this project using `com.opower.unitsofmeasure` groupId, so I'm totally fine, and actually would prefer, if it's moved under your space (`tec.uom` or similar).
_json-b_ is fine, but Jackson is so widespread and popular that it just has to be supported as well by you, or maybe by Jackson community in their space. Actually, if you like the latter, I can discuss it with Jackson guys.
But otherwise, yes, I can contribute, and my use case - we have tons of projects, all use Jackson. We're using JSR 275 (we wrote our own (de)serializers), and I wanted to switch to JSR 363. Since you already support Jackson, I wanted just re-use that - result is this discussion. :)

**Comment by keilw** [comment]
A simple migration of the Opower library could be problematic at least we may have to dual-license that MIT (the existing license) and BSD. Otherwise I see no problem using the existing Opower project as inspiration or basis.

**Comment by jeffkole** [comment]
Neither Opower nor I are maintaining this repo.  From the readme, it looks like it was dependent on an internal build of JScience, so the likelihood of it working externally is small.  I'm frankly surprised anyone forked it at all.  At this point, I would recommend using the project as inspiration in your own fork that is properly managed.

**Comment by keilw** [comment]
It works because the dependencies are now the officially released Final JSR 363 (JScience was once intended to be RI of a never finalized JSR 275) 
If you see no problem having the fork use BSD3 (like almost everything else) we'd be happy to offer a Jackson variant under the UoM umbrella.

**Comment by jeffkole** [comment]
Fork away!

**Comment by ptahchiev** [comment]
Any updates here?

**Comment by keilw** [comment]
This one is on JCenter already: https://bintray.com/unitsofmeasurement/maven/com.opower.unitsofmeasure%3Ajackson-module-unitsofmeasure/1.3.4 I don't think we are going to move it to the old tec.uom namespace any more, hence the update is likely to happen based on Indriya/JSR 385. For uom-se the 1.3.x versions will work fine, we just can't mirror it to MavenCentral because the com.opower namespace is now owened by Oracle.

**Comment by keilw** [comment]
@ptahchiev What about using https://github.com/unitsofmeasurement/uom-lib, would you be happy with that based on indriya? For backward compatibility with e.g. Jadira JPA the most recent (0.9) generation of SI Units or UoM Systems use the JSR 363 compliant Indriya 1.0 while later versions should probably migrate to the new `tech.units.indriya` branch leading towards 2.0. 
I could imagine doing a `tec.uom.lib` 1.0.x build for this if you are happy to use that for Jackson?

**Comment by ptahchiev** [comment]
@keilw  yes, I believe this is the right way to go - having all uom-related projects under the same namespace in maven central would be great.

**Comment by keilw** [comment]
@jeffkole Btw. if the original repository is no longer actively maintained, maybe you might consider archiving it?

**Comment by jeffkole** [comment]
Good call.  Done.

**Comment by keilw** [comment]
Closing this, already to JCenter, the successor should also be made available on MavenCentral.
