### ISSUE TITLE
Serialization appears to include superscripts

### ISSUE THREAD

**Issue by cacsar** [unitsofmeasurement/jackson-module-unitsofmeasure#9]
In trying to serialize UCUM.GALLON_US I got `(c(cm*254.0)³)*231.0` (note the superscript 3), while I expected [gal_us] its absence is understandable given that the unit doesn't have a symbol set explicitly. In my attempt to read the UCUM spec it seemed as though only 7 bit ASCII is used for the representations and that `(c(cm*254.0)3)*231.0` or `(c(cm*254.0)+3)*231.0` would be expected instead.

**Comment by keilw** [comment]
With serialize I assume you also use `toString()` at some point, directly or indirectly?
Using `UCUMFormat` instead of (the built-in) SimpleUnitFormat/toString you'll get `[gal_us]`. 
`SimpleUnitFormat` also has an ASCII variant. While it is not so widely used, could you give it a try, it is not suppossed to return any non-ASCII characters. Please give it a try. If you did end up with a non-ASCII format, please file an issue in https://github.com/unitsofmeasurement/uom-se/issues.

This is still a few months down the road, but I created an issue for the next generation Unified RI https://github.com/unitsofmeasurement/indriya/issues/2 to allow a bit of flexibility between `toString()` methods, e.g. restricting to use just ASCII characters or even take the `Locale` into consideration if you need to.

**Comment by cacsar** [comment]
My apologies and thank you for your help, it appears that my testing was quite inadequate and I had not examined how JSON serialization worked for Map by default. I can confirm that I can get [gal_us] when I serialize Unit directly.
